---

- name: download war file
  get_url: url=https://github.com/takezoe/gitbucket/releases/download/{{ git_bucket_version }}/gitbucket.war 
           dest=/tmp/{{ application_name }}.war

- name: stop jetty
  service: name=jetty state=stopped
  notify: restart jetty

- name: deploy war file
  copy: src=/tmp/{{ application_name }}.war dest={{ jetty_home }}/webapps/
